# Pins definitions

# Analog input
PH_SENSOR_PIN = 0
TDS_SENSOR_PIN = 1
WATER_LEVEL_PIN = 2
NUTRIENT_LEVEL = 3
PH_DOWNER_LEVEL_PIN = 4

# Digital output
WATER_PUMP_PIN = 22
NUTRIENT_PUMP_PIN = 23
PH_DOWNER_PUMP_PIN = 24
MIXER_PUMP_PIN = 25
