
@startuml

state "Idle" as IDLE
state "Water pump ON" as WATER_PUMP_ON
state "Up nutrient level" as UP_NUTRIENT_LEVEL
state "Mix nutrient liquid" as MIX_NUTRIENT_LIQUID
state "Down pH level" as DOWN_PH_LEVEL
state "Mix pH downer liquid" as MIX_PH_DOWNER_LIQUID

IDLE --> UP_NUTRIENT_LEVEL
note on link
[T1]
tds <= min_tds_level

nutrient_time = millis()
mix_time = millis()

ON Nutrient pump
ON Mixer pump
end note

UP_NUTRIENT_LEVEL --> MIX_NUTRIENT_LIQUID
note on link
[T2]
(millis() - nutrient_time) > MAX_NUTRIENT_PERIOD * 1000

OFF Nutrient pump
end note

MIX_NUTRIENT_LIQUID --> UP_NUTRIENT_LEVEL
note on link
[T3]
(
    (millis() - mix_time) > MIX_LOCK * 1000
    &
    ( tds <= min_tds_level )
)

nutrient_time = millis()
mix_time = millis()

ON Nutrient pump
end note

MIX_NUTRIENT_LIQUID --> IDLE
note on link
[T4]
tds >= max_tds_level

OFF Nutrient pump
OFF Mixer pump
end note

IDLE --> DOWN_PH_LEVEL
note on link
[T5]
ph >= max_ph_level

ph_downer_time = millis()
mix_time = millis()

ON pH downer pump
ON Mixer pump
end note

DOWN_PH_LEVEL --> MIX_PH_DOWNER_LIQUID
note on link
[T6]
(millis() - ph_downer_time) > MAX_PH_DOWNER_PERIOD * 1000

OFF pH downer pump
end note

MIX_PH_DOWNER_LIQUID --> DOWN_PH_LEVEL
note on link
[T7]
(
    (millis() - mix_time) > MIX_LOCK * 1000
    &
    ph >= max_ph_level
)

ph_downer_time = millis()
mix_time = millis()

ON pH downer pump
end note


MIX_PH_DOWNER_LIQUID --> IDLE
note on link
[T8]
ph <= min_ph_level

OFF pH downer pump
OFF Mixer pump
end note

IDLE --> WATER_PUMP_ON
note on link
[T9]
water_required == true

ON water pump
end note

WATER_PUMP_ON --> IDLE
note on link
[T9]
water_required == false

OFF water pump
end note

@enduml